<?php

namespace Bitrix\Bizproc\Api\Enum;

use Bitrix\Main\Localization\Loc;
use Bitrix\Bizproc\Error;

Loc::loadMessages(__FILE__);

enum ErrorMessage: string
{
	case BP_NO_ACCESS = 'BP_NO_ACCESS';
	case ROBOTS_NO_ACCESS = 'ROBOTS_NO_ACCESS';
	case TEMPLATE_NO_PRERMISSIONS = 'TEMPLATE_NO_PRERMISSIONS';
	case START_ACCESS_DENIED = 'START_ACCESS_DENIED';
	case VIEW_RIGHTS_ERROR = 'VIEW_RIGHTS_ERROR';
	case RESULT_NO_RIGHTS_VIEW = 'RESULT_NO_RIGHTS_VIEW';
	case ACCESS_DENIED = 'ACCESS_DENIED';
	case ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND';
	case BP_NOT_FOUND = 'BP_NOT_FOUND';
	case TASK_NOT_FOUND = 'TASK_NOT_FOUND';
	case ACTIVITY_ERROR = 'ACTIVITY_ERROR';
	case NO_ENTITY = 'NO_ENTITY';
	case EMPTY_DOCUMENT = 'EMPTY_DOCUMENT';
	case USER_NOT_FOUND = 'USER_NOT_FOUND';
	case ACTIVITY_NOT_FOUND = 'ACTIVITY_NOT_FOUND';
	case TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND';
	case ENTITY_NOT_EXISTS = 'ENTITY_NOT_EXISTS';
	case INVALID_TYPE = 'INVALID_TYPE';
	case INVALID_FILE = 'INVALID_FILE';
	case EMPTY_TEMPLATE = 'EMPTY_TEMPLATE';
	case EMPTY_PROP = 'EMPTY_PROP';
	case INVALID_PARAM_TYPE = 'INVALID_PARAM_TYPE';
	case INVALID_PARAM_ARG = 'INVALID_PARAM_ARG';
	case PARAM_REQUIRED = 'PARAM_REQUIRED';
	case MODULE_NOT_INSTALLED = 'MODULE_NOT_INSTALLED';
	case WRONG_TEMPLATE = 'WRONG_TEMPLATE';
	case UNKNOWN_ERROR = 'UNKNOWN_ERROR';
	case DOCUMENT_TYPE_ERROR = 'DOCUMENT_TYPE_ERROR';
	case GET_DATA_ERROR = 'GET_DATA_ERROR';
	case CREATE_WORKFLOW = 'CREATE_WORKFLOW';
	case INVALID_USER_ID = 'INVALID_USER_ID';
	case IMPORT_ACCESS_DENIED = 'IMPORT_ACCESS_DENIED';
	case EXPORT_ACCESS_DENIED = 'EXPORT_ACCESS_DENIED';

	public function get(array $replace = []): string
	{
		return match ($this) {
			//ACCESS_DENIED
			self::BP_NO_ACCESS => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_BP_NO_ACCESS'),
			self::ROBOTS_NO_ACCESS => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_ROBOTS_NO_ACCESS'),
			self::TEMPLATE_NO_PRERMISSIONS => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_TEMPLATE_NO_PRERMISSIONS'),
			self::START_ACCESS_DENIED => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_START_ACCESS_DENIED'),
			self::VIEW_RIGHTS_ERROR => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_VIEW_RIGHTS_ERROR'),
			self::RESULT_NO_RIGHTS_VIEW => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_RESULT_NO_RIGHTS_VIEW'),
			self::ACCESS_DENIED => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_ACCESS_DENIED'),
			self::DOCUMENT_TYPE_ERROR => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_DOCUMENT_TYPE_ERROR'),
			self::IMPORT_ACCESS_DENIED => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_IMPORT_ACCESS_DENIED'),
			self::EXPORT_ACCESS_DENIED => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_EXPORT_ACCESS_DENIED'),

			//NOT_FOUND
			self::BP_NOT_FOUND => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_BP_NOT_FOUND'),
			self::TASK_NOT_FOUND => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_TASK_NOT_FOUND'),
			self::NO_ENTITY => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_NO_ENTITY'),
			self::EMPTY_DOCUMENT => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_EMPTY_DOCUMENT'),
			self::USER_NOT_FOUND => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_USER_NOT_FOUND', $replace),
			self::ACTIVITY_NOT_FOUND => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_ACTIVITY_NOT_FOUND', $replace),
			self::TEMPLATE_NOT_FOUND => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_TEMPLATE_NOT_FOUND', $replace),
			self::ENTITY_NOT_EXISTS => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_ENTITY_NOT_EXISTS'),
			self::GET_DATA_ERROR => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_GET_DATA_ERROR'),
			self::CREATE_WORKFLOW => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_CREATE_WORKFLOW'),
			self::INVALID_USER_ID => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_INVALID_USER_ID'),

			//VALIDATION
			self::INVALID_TYPE => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_INVALID_TYPE'),
			self::INVALID_FILE => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_INVALID_FILE'),
			self::EMPTY_TEMPLATE => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_EMPTY_TEMPLATE', $replace),
			self::EMPTY_PROP => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_EMPTY_PROP', $replace),
			self::INVALID_PARAM_TYPE => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_INVALID_PARAM_TYPE', $replace),
			self::INVALID_PARAM_ARG => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_INVALID_PARAM_ARG', $replace),
			self::PARAM_REQUIRED => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_PARAM_REQUIRED', $replace),

			//SYSTEM
			self::MODULE_NOT_INSTALLED => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_MODULE_NOT_INSTALLED'),
			self::WRONG_TEMPLATE => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_WRONG_TEMPLATE'),
			self::UNKNOWN_ERROR => Loc::getMessage('BIZPROC_API_ENUM_ERRORS_UNKNOWN_ERROR'),
		};
	}

	public function getError(array $replace = [], $code = 0, $customData = null): Error
	{
		return new Error($this->get($replace), $code, $customData);
	}
}
