<?php

namespace Bitrix\UI\Buttons;

abstract class Icon
{
	public const UNFOLLOW = 'ui-btn-icon-unfollow';
	public const FOLLOW = 'ui-btn-icon-follow';
	public const ADD = 'ui-btn-icon-add';
	public const STOP = 'ui-btn-icon-stop';
	public const START = 'ui-btn-icon-start';
	public const PAUSE = 'ui-btn-icon-pause';
	public const ADD_FOLDER = 'ui-btn-icon-add-folder';
	public const SETTING = 'ui-btn-icon-setting';
	public const SETTINGS = 'ui-btn-icon-setting';
	public const TASK = 'ui-btn-icon-task';
	public const INFO = 'ui-btn-icon-info';
	public const SEARCH = 'ui-btn-icon-search';
	public const PRINT = 'ui-btn-icon-print';
	public const PRINTER = 'ui-btn-icon-print';
	public const LIST = 'ui-btn-icon-list';
	public const MENU = 'ui-btn-icon-list';
	public const BUSINESS = 'ui-btn-icon-business';
	public const BUSINESS_CONFIRM = 'ui-btn-icon-business-confirm';
	public const BUSINESS_WARNING = 'ui-btn-icon-business-warning';
	public const CAMERA = 'ui-btn-icon-camera';
	public const PHONE_UP = 'ui-btn-icon-phone-up';
	public const PHONE_DOWN = 'ui-btn-icon-phone-down';
	public const PHONE_CALL = 'ui-btn-icon-phone-call';
	public const BACK = 'ui-btn-icon-back';
	public const REMOVE = 'ui-btn-icon-remove';
	public const DOWNLOAD = 'ui-btn-icon-download';
	public const DOTS = 'ui-btn-icon-dots';
	public const DONE = 'ui-btn-icon-done';
	public const CANCEL = 'ui-btn-icon-cancel';
	public const DISK = 'ui-btn-icon-disk';
	public const LOCK = 'ui-btn-icon-lock';
	public const MAIL = 'ui-btn-icon-mail';
	public const CHAT = 'ui-btn-icon-chat';
	public const PAGE = 'ui-btn-icon-page';
	public const CLOUD = 'ui-btn-icon-cloud';
	public const EDIT = 'ui-btn-icon-edit';
	public const SHARE = 'ui-btn-icon-share';
	public const ANGLE_UP = 'ui-btn-icon-angle-up';
	public const ANGLE_DOWN = 'ui-btn-icon-angle-down';
	public const EYE_OPENED = 'ui-btn-icon-eye-opened';
	public const EYE_CLOSED = 'ui-btn-icon-eye-closed';
	public const ALERT = 'ui-btn-icon-alert';
	public const FAIL = 'ui-btn-icon-fail';
	public const SUCCESS = 'ui-btn-icon-success';
	public const PLAN = 'ui-btn-icon-plan';
	public const TARIFF = 'ui-btn-icon-tariff';
	public const BATTERY = 'ui-btn-icon-battery';
	public const NO_BATTERY = 'ui-btn-icon-no-battery';
	public const HALF_BATTERY = 'ui-btn-icon-half-battery';
	public const LOW_BATTERY = 'ui-btn-icon-low-battery';
	public const CRIT_BATTERY = 'ui-btn-icon-crit-battery';
	public const DEMO = 'ui-btn-icon-demo';
	public const ROBOTS = 'ui-btn-icon-robots';
	public const NOTE = 'ui-btn-icon-note';
	public const SCRIPT = 'ui-btn-icon-script';
	public const PRINT2 = 'ui-btn-icon-print-2';
	public const FUNNEL = 'ui-btn-icon-funnel';
	public const AI = 'ui-btn-icon-ai ui-icon-set__scope';
	public const BUSINESS_NEW = 'ui-btn-icon-business-new';
	public const RELOAD = 'ui-btn-icon-reload';
	public const CITY = 'ui-btn-icon-city';
	public const TWO_PERSONS = 'ui-btn-icon-two-persons';
	public const COPILOT = 'ui-btn-icon-copilot';
}
